#!/bin/bash

./mem.bash&pid0=$!

rm table1
echo  "Time MEM Virt Res SHR CPU free" >> table1
echo "mem.bash $pid0"

for ((;;)) do
	line=$(top -p $pid0 -b -n 1 | head -8 | tail -n +8 )
	free=$(top -o %MEM -b -n 1 | head -4 | tail -n +4 | awk '{print ""$6""}')
	line=$(echo -e $line | awk '{print ""$11" "$10" "$5" "$6" "$7" "$9""}')
	line=$(echo -e "$line $free\n")
	echo $line >> table1
done
