#!/bin/bash

while true; do
	read line
	
	if [[ "$line" == "QUIT" ]];then
		echo "QUIT" >pipe
		exit 0
	fi

	if [[ "$line" != "+" && "$line" != "*" && ! "$line" =~ [0-9]+ ]]; then
		echo "Invalid Data"
		echo "QUIT" >pipe
		exit 1
	fi

	echo "$line" > pipe
done
