#!/bin/bash

LastBackupDate=$( ls $HOME | grep -E "^Backup-" | sort -n | tail -l | sed 's/^Backup-//')
LastBackupName="$HOME/Backup-$LastBackupDate"

for file in $(ls $LastBackupName); do
	echo $file
done
echo $second
