#!/bin/bash

LastBackupDate=$( ls $HOME | grep -E "^Backup-" | sort -n | tail -1 | sed 's/^Backup-//')
LastBackupName="$HOME/Backup-$LastBackupDate"

if [[ $LastBackupDate == "" ]]; then
	echo "There are no backups"
	exit 1
fi

if [[ ! -d $HOME/restore ]]; then
	mkdir $HOME/restore
fi

for file in $(ls $LastBackupName); do
	later=$(ls $LastBackupName | grep -E "^"$file."[0-9]{4}-[0-9]{2}-[0-9]{2}$")
	if [[ $later != "" ]]; then
		continue
	fi
	cp "$LastBackupName/$file" "$HOME/restore/$file"
done
